### ISSUE TITLE
scommit errors when there has been no commits to a remote from a local yet

### ISSUE THREAD

**Issue by sincethestudy** [Globe-Engineer/semantic-commit#1]
`scommit
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/opt/homebrew/bin/scommit", line 8, in <module>
    sys.exit(scommit())
             ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scommit/scommit.py", line 58, in scommit
    diff = subprocess.check_output(['git', 'diff', 'HEAD'], text=True).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'diff', 'HEAD']' returned non-zero exit status 128.`

**Comment by sincethestudy** [comment]
solved
